language: ruby
rvm:
  - 1.8.7
  - 2.2.0
matrix:
  allow_failures:
    - rvm: 2.2.0
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.7.4
  - PUPPET_VERSION=2.7.17
notifications:
  email: false
gemfile: Gemfile
